version: '3.8'

services:
  crawler:
    build: .
    container_name: gamemarket-crawler
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=crawler
      - DB_PASSWORD=crawler_pass
      - DB_NAME=gamemarket
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - crawler-network

  mysql:
    image: mysql:8.0
    container_name: gamemarket-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gamemarket
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawler_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - crawler-network

  redis:
    image: redis:7-alpine
    container_name: gamemarket-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - crawler-network

  nginx:
    image: nginx:alpine
    container_name: gamemarket-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/export:/usr/share/nginx/html/data
    depends_on:
      - crawler
    networks:
      - crawler-network

volumes:
  mysql_data:
  redis_data:

networks:
  crawler-network:
    driver: bridge 