version: '3.8'

services:
  crawler:
    build: .
    container_name: gamemarket-crawler
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=crawler
      - DB_PASSWORD=crawler_pass
      - DB_NAME=gamemarket
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - crawler-network

  mysql:
    image: mysql:8.0
    container_name: gamemarket-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gamemarket
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawler_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - crawler-network

  redis:
    image: redis:7-alpine
    container_name: gamemarket-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - crawler-network

  web:
    build: .
    container_name: gamemarket-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=crawler
      - MYSQL_PASSWORD=crawler_pass
      - MYSQL_DATABASE=gamemarket
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DATABASE=gamemarket
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis
      - mongo
    networks:
      - crawler-network
    command: python run_web.py --host 0.0.0.0 --port 8080 --env production

  mongo:
    image: mongo:7
    container_name: gamemarket-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_pass
      MONGO_INITDB_DATABASE: gamemarket
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - crawler-network

  nginx:
    image: nginx:alpine
    container_name: gamemarket-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/export:/usr/share/nginx/html/data
    depends_on:
      - web
      - crawler
    networks:
      - crawler-network

volumes:
  mysql_data:
  redis_data:
  mongo_data:

networks:
  crawler-network:
    driver: bridge 