name: gamemarket_crawler
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - scrapy==2.11.0
    - scrapy-redis==0.7.3
    - scrapy-playwright==0.0.34
    - playwright==1.40.0
    - pandas==2.1.4
    - numpy==1.24.3
    - pymongo==4.6.0
    - redis==5.0.1
    - beautifulsoup4==4.12.2
    - requests==2.31.0
    - python-dotenv==1.0.0
    - pyyaml==6.0.1
    - loguru==0.7.2
    - tqdm==4.66.1
    - click==8.1.7
    - rich==13.7.0
    - fake-useragent==1.4.0
    - pydantic==2.5.2 